### ISSUE TITLE
sh run.sh报错，请问怎么解决

### ISSUE THREAD

**Issue by gys18007141407** [ACL2020SpellGCN/SpellGCN#9]
``Traceback (most recent call last):
  File "../run_spellgcn.py", line 1310, in <module>
    tf.app.run()
  File "C:\Users\gys14\anaconda3\envs\spellgcn\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "../run_spellgcn.py", line 1012, in main
    bert_config = modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
  File "D:\PycharmProjects\SpellGCN-master\modeling.py", line 93, in from_json_file
    text = reader.read()
  File "C:\Users\gys14\anaconda3\envs\spellgcn\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\gys14\anaconda3\envs\spellgcn\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\gys14\anaconda3\envs\spellgcn\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:/Program Files/Git/home/fanyin.cxy/chinese_L-12_H-768_A-12/bert_config.json : \u03f5\u0373\udcd5\u04b2\udcbb\udcb5\udcbd\u05b8\udcb6\udca8\udcb5\udcc4��\udcbe\udcb6\udca1\udca3

; No such process

**Comment by li-aolong** [comment]
要用`/chinese_L-12_H-768_A-12`这个文件的，得改成自己的路径
